name: Docker Build and Send Image

on:
  workflow_call:
      inputs:
        path_repos_build:
          description: test de uso do image_repo
          default: "echo 'there is no extra cmds to run'"
          required: false
          type: string  

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#   PR_NUMBER: "${{ github.event.number }}"
#   REPOS: "${{ github.repository }}"

jobs:

  Using-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testando o test
        run: |
          ${{ inputs.path_repos_build }}
          for i in $(echo -e $repos); do echo $i ; done

