name: Testando variaveis

on:
  workflow_call:
      inputs:
        image_repo:
          description: Image name to build and upload to HPE repository
          default: "echo 'Image name not definied'"
          required: false
          type: string

        path_repos_build:
          description: test de uso do image_repo
          default: "echo 'Put available repo path to compile code'"
          required: false
          type: string

        create_folders_to_build:
          description: Preparing folders for image build
          default: "echo 'Folders for the build image were not created'"
          required: false
          type: string  

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# env:
#   PR_NUMBER: "${{ github.event.number }}"
#   REPOS: "${{ github.repository }}"

jobs:

  Using-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testando o test
        run: |
          ${{ inputs.path_repos_build }} && ${{ inputs.image_repo }} && ${{ inputs.create_folders_to_build }}
          echo $IMAGE_REPO
          for i in $(echo -e $repos); do echo $i ; done
      - name: Novo test
        run: |
          echo $IMAGE_REPO
          for i in $(echo -e $repos); do echo $i ; done
      - name: Teste usando variavel
        run: |
          echo "${{ env.roney_test }}"


