name: Docker Build and Send Image

on:
  workflow_call:
      inputs:
        image_repo:
          description: test de uso do image_repo
          default: "echo 'there is no extra cmds to run'"
          required: false
          type: string  

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  PR_NUMBER: "${{ github.event.number }}"
  REPOS: "${{ github.repository }}"
  path_repos_RoneySantos/lab-notifier-jenkins-ia: 'api-gateway/cmd/apigw/\nauthentication/cmd/accounts/'
  RONEY: ${{ inputs.image_repo }}

jobs:

  Using-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Testando o test
        run: |
          ${{ inputs.image_repo }}
          echo $repos
      

